import { godotRidGetId, type GodotRid } from './gdscript-builtins';
import { registerGodotObjectIdentity } from './object';

export type GodotDofQuality = 'very-low' | 'low' | 'medium' | 'high';
export interface GodotDepthOfFieldDescriptor { readonly viewport: GodotRid; readonly enabled?: boolean; readonly focusDistance?: number; readonly focalLength?: number; readonly aperture?: number; readonly nearEnabled?: boolean; readonly nearDistance?: number; readonly nearTransition?: number; readonly farEnabled?: boolean; readonly farDistance?: number; readonly farTransition?: number; readonly amount?: number; readonly quality?: GodotDofQuality; readonly jitter?: boolean; readonly autofocus?: boolean; readonly autofocusSpeed?: number; readonly autofocusMin?: number; readonly autofocusMax?: number; readonly userData?: unknown }
export interface GodotDepthOfFieldState extends Required<Omit<GodotDepthOfFieldDescriptor, 'userData'>> { readonly source: GodotRid | null; readonly depth: GodotRid | null; readonly destination: GodotRid | null; readonly currentFocusDistance: number; readonly targetFocusDistance: number; readonly lastRenderedFrame: number; readonly generation: number; readonly userData: unknown }
export interface GodotDepthOfFieldBackend { sampleFocus?(frame: number, state: GodotDepthOfFieldState): number | Promise<number>; renderNear(frame: number, state: GodotDepthOfFieldState): void | Promise<void>; renderFar(frame: number, state: GodotDepthOfFieldState): void | Promise<void>; composite(frame: number, state: GodotDepthOfFieldState): void | Promise<void> }
export interface GodotDepthOfFieldFrameResult { readonly frame: number; readonly rendered: readonly GodotRid[]; readonly skipped: readonly GodotRid[]; readonly passes: number; readonly failed: readonly { viewport: GodotRid; error: unknown }[] }
export interface GodotDepthOfFieldSnapshot { readonly frame: number; readonly viewports: readonly GodotDepthOfFieldState[]; readonly enabled: number; readonly autofocus: number; readonly renderedFrames: number; readonly passes: number; readonly generation: number; readonly lastFrame: GodotDepthOfFieldFrameResult | null }
interface Entry { viewport: GodotRid; enabled: boolean; focusDistance: number; focalLength: number; aperture: number; nearEnabled: boolean; nearDistance: number; nearTransition: number; farEnabled: boolean; farDistance: number; farTransition: number; amount: number; quality: GodotDofQuality; jitter: boolean; autofocus: boolean; autofocusSpeed: number; autofocusMin: number; autofocusMax: number; source: GodotRid | null; depth: GodotRid | null; destination: GodotRid | null; currentFocusDistance: number; targetFocusDistance: number; lastRenderedFrame: number; generation: number; userData: unknown; order: number }
function integer(value: unknown, member: string, minimum = 0): number { const result = Number(value); if (!Number.isSafeInteger(result) || result < minimum) throw new RangeError(`godot-compat: DepthOfFieldRuntime.${member} requires integer >= ${minimum}.`); return result; }
function finite(value: unknown, member: string, minimum = -Infinity, maximum = Infinity): number { const result = Number(value); if (!Number.isFinite(result) || result < minimum || result > maximum) throw new RangeError(`godot-compat: DepthOfFieldRuntime.${member} requires finite value in [${minimum}, ${maximum}].`); return result; }
function bool(value: unknown, member: string): boolean { if (typeof value !== 'boolean') throw new TypeError(`godot-compat: DepthOfFieldRuntime.${member} requires bool.`); return value; }
function rid(value: unknown): GodotRid { if (value === null || typeof value !== 'object') throw new TypeError('godot-compat: DepthOfFieldRuntime requires RID.'); godotRidGetId(value); return value as GodotRid; }
function quality(value: unknown): GodotDofQuality { if (value !== 'very-low' && value !== 'low' && value !== 'medium' && value !== 'high') throw new TypeError('godot-compat: unknown depth-of-field quality.'); return value; }
function state(entry: Entry): GodotDepthOfFieldState { return Object.freeze({ ...entry }); }

export class GodotDepthOfFieldRuntime {
  public readonly __godotClass = 'DepthOfFieldRuntime'; private readonly backend: GodotDepthOfFieldBackend; private readonly entries = new Map<bigint, Entry>(); private readonly watchers = new Set<(snapshot: GodotDepthOfFieldSnapshot) => void>();
  private frameValue = 0; private nextOrder = 0; private generationValue = 0; private renderedFrames = 0; private passes = 0; private processing = false; private lastFrame: GodotDepthOfFieldFrameResult | null = null;
  public constructor(backend: GodotDepthOfFieldBackend) { if (typeof backend?.renderNear !== 'function' || typeof backend?.renderFar !== 'function' || typeof backend?.composite !== 'function') throw new TypeError('godot-compat: DepthOfFieldRuntime requires render backend.'); this.backend = backend; registerGodotObjectIdentity(this, 'DepthOfFieldRuntime'); }
  public addViewport(value: GodotDepthOfFieldDescriptor): void { const viewport = rid(value.viewport), id = godotRidGetId(viewport); if (this.entries.has(id)) throw new Error('godot-compat: depth-of-field viewport already exists.'); const focus = finite(value.focusDistance ?? 10, 'focus_distance', Number.MIN_VALUE), autofocusMin = finite(value.autofocusMin ?? 0.1, 'autofocus_min', Number.MIN_VALUE), autofocusMax = finite(value.autofocusMax ?? 1000, 'autofocus_max', autofocusMin); this.entries.set(id, { viewport, enabled: bool(value.enabled ?? true, 'enabled'), focusDistance: focus, focalLength: finite(value.focalLength ?? 50, 'focal_length', Number.MIN_VALUE), aperture: finite(value.aperture ?? 2.8, 'aperture', Number.MIN_VALUE), nearEnabled: bool(value.nearEnabled ?? false, 'near_enabled'), nearDistance: finite(value.nearDistance ?? 2, 'near_distance', 0), nearTransition: finite(value.nearTransition ?? 1, 'near_transition', 0), farEnabled: bool(value.farEnabled ?? true, 'far_enabled'), farDistance: finite(value.farDistance ?? 10, 'far_distance', 0), farTransition: finite(value.farTransition ?? 5, 'far_transition', 0), amount: finite(value.amount ?? 0.1, 'amount', 0, 1), quality: quality(value.quality ?? 'medium'), jitter: bool(value.jitter ?? true, 'jitter'), autofocus: bool(value.autofocus ?? false, 'autofocus'), autofocusSpeed: finite(value.autofocusSpeed ?? 4, 'autofocus_speed', 0), autofocusMin, autofocusMax, source: null, depth: null, destination: null, currentFocusDistance: focus, targetFocusDistance: focus, lastRenderedFrame: -1, generation: 1, userData: value.userData ?? null, order: this.nextOrder++ }); this.generationValue += 1; this.publish(); }
  public removeViewport(value: unknown): boolean { const viewport = rid(value), removed = this.entries.delete(godotRidGetId(viewport)); if (removed) { this.generationValue += 1; this.publish(); } return removed; }
  private requireEntry(value: unknown): Entry { const viewport = rid(value), entry = this.entries.get(godotRidGetId(viewport)); if (entry === undefined) throw new Error('godot-compat: depth-of-field viewport does not exist.'); return entry; }
  public setTargets(value: unknown, sourceValue: unknown, depthValue: unknown, destinationValue: unknown): void { const entry = this.requireEntry(value); entry.source = rid(sourceValue); entry.depth = rid(depthValue); entry.destination = rid(destinationValue); this.publish(); }
  public updateViewport(value: unknown, patch: Partial<Omit<GodotDepthOfFieldDescriptor, 'viewport'>>): void { const entry = this.requireEntry(value); if (patch.enabled !== undefined) entry.enabled = bool(patch.enabled, 'enabled'); if (patch.focusDistance !== undefined) entry.focusDistance = finite(patch.focusDistance, 'focus_distance', Number.MIN_VALUE); if (patch.focalLength !== undefined) entry.focalLength = finite(patch.focalLength, 'focal_length', Number.MIN_VALUE); if (patch.aperture !== undefined) entry.aperture = finite(patch.aperture, 'aperture', Number.MIN_VALUE); if (patch.nearEnabled !== undefined) entry.nearEnabled = bool(patch.nearEnabled, 'near_enabled'); if (patch.nearDistance !== undefined) entry.nearDistance = finite(patch.nearDistance, 'near_distance', 0); if (patch.nearTransition !== undefined) entry.nearTransition = finite(patch.nearTransition, 'near_transition', 0); if (patch.farEnabled !== undefined) entry.farEnabled = bool(patch.farEnabled, 'far_enabled'); if (patch.farDistance !== undefined) entry.farDistance = finite(patch.farDistance, 'far_distance', 0); if (patch.farTransition !== undefined) entry.farTransition = finite(patch.farTransition, 'far_transition', 0); if (patch.amount !== undefined) entry.amount = finite(patch.amount, 'amount', 0, 1); if (patch.quality !== undefined) entry.quality = quality(patch.quality); if (patch.jitter !== undefined) entry.jitter = bool(patch.jitter, 'jitter'); if (patch.autofocus !== undefined) entry.autofocus = bool(patch.autofocus, 'autofocus'); if (patch.autofocusSpeed !== undefined) entry.autofocusSpeed = finite(patch.autofocusSpeed, 'autofocus_speed', 0); if (patch.autofocusMin !== undefined) entry.autofocusMin = finite(patch.autofocusMin, 'autofocus_min', Number.MIN_VALUE); if (patch.autofocusMax !== undefined) entry.autofocusMax = finite(patch.autofocusMax, 'autofocus_max', entry.autofocusMin); if (patch.userData !== undefined) entry.userData = patch.userData; entry.generation += 1; this.publish(); }
  public async processFrame(frameValue: unknown, deltaValue: unknown): Promise<GodotDepthOfFieldFrameResult> { const frame = integer(frameValue, 'frame'), delta = finite(deltaValue, 'delta', 0); if (frame < this.frameValue) throw new RangeError('godot-compat: depth-of-field frame cannot move backwards.'); if (this.processing) throw new Error('godot-compat: depth-of-field frame already processing.'); this.frameValue = frame; this.processing = true; const rendered: GodotRid[] = [], skipped: GodotRid[] = [], failed: Array<{ viewport: GodotRid; error: unknown }> = []; let framePasses = 0; try { for (const entry of [...this.entries.values()].sort((left, right) => left.order - right.order)) { if (!entry.enabled || entry.source === null || entry.depth === null || entry.destination === null || (!entry.nearEnabled && !entry.farEnabled)) { skipped.push(entry.viewport); continue; } try { if (entry.autofocus && this.backend.sampleFocus !== undefined) entry.targetFocusDistance = Math.max(entry.autofocusMin, Math.min(entry.autofocusMax, finite(await this.backend.sampleFocus(frame, state(entry)), 'sampled_focus', 0))); else entry.targetFocusDistance = entry.focusDistance; const weight = 1 - Math.exp(-entry.autofocusSpeed * delta); entry.currentFocusDistance += (entry.targetFocusDistance - entry.currentFocusDistance) * weight; if (entry.nearEnabled) { await this.backend.renderNear(frame, state(entry)); framePasses += 1; } if (entry.farEnabled) { await this.backend.renderFar(frame, state(entry)); framePasses += 1; } await this.backend.composite(frame, state(entry)); framePasses += 1; entry.lastRenderedFrame = frame; entry.generation += 1; rendered.push(entry.viewport); } catch (error) { failed.push(Object.freeze({ viewport: entry.viewport, error })); } } this.renderedFrames += 1; this.passes += framePasses; this.lastFrame = Object.freeze({ frame, rendered: Object.freeze(rendered), skipped: Object.freeze(skipped), passes: framePasses, failed: Object.freeze(failed) }); this.publish(); return this.lastFrame; } finally { this.processing = false; } }
  public getSnapshot(): GodotDepthOfFieldSnapshot { const viewports = [...this.entries.values()].map(state); return Object.freeze({ frame: this.frameValue, viewports: Object.freeze(viewports), enabled: viewports.filter((entry) => entry.enabled).length, autofocus: viewports.filter((entry) => entry.autofocus).length, renderedFrames: this.renderedFrames, passes: this.passes, generation: this.generationValue, lastFrame: this.lastFrame }); }
  public watch(watcher: (snapshot: GodotDepthOfFieldSnapshot) => void): () => void { this.watchers.add(watcher); watcher(this.getSnapshot()); return () => this.watchers.delete(watcher); }
  private publish(): void { const value = this.getSnapshot(); for (const watcher of this.watchers) watcher(value); }
  public clear(): void { if (this.processing) throw new Error('godot-compat: cannot clear depth-of-field during frame.'); this.entries.clear(); this.lastFrame = null; this.generationValue += 1; this.publish(); }
  public dispose(): void { this.clear(); this.watchers.clear(); }
}

export function createGodotDepthOfFieldRuntime(backend: GodotDepthOfFieldBackend): GodotDepthOfFieldRuntime { return new GodotDepthOfFieldRuntime(backend); }
