/** Godot PhysicsServer3DExtension protocol over an exact project physics server. */

import { registerGodotObjectIdentity } from './object';

export interface GodotPhysicsServer3DExtensionCarrier { invoke(method: string, args: readonly unknown[]): unknown }

export class GodotPhysicsServer3DExtension {
  constructor(private readonly carrier: GodotPhysicsServer3DExtensionCarrier) { registerGodotObjectIdentity(this, 'PhysicsServer3DExtension'); }
  private call(method: string, args: readonly unknown[]): any { return this.carrier.invoke(method, args); }
  _world_boundary_shape_create(...args: readonly unknown[]): any { return this.call('_world_boundary_shape_create', args); }
  _separation_ray_shape_create(...args: readonly unknown[]): any { return this.call('_separation_ray_shape_create', args); }
  _sphere_shape_create(...args: readonly unknown[]): any { return this.call('_sphere_shape_create', args); }
  _box_shape_create(...args: readonly unknown[]): any { return this.call('_box_shape_create', args); }
  _capsule_shape_create(...args: readonly unknown[]): any { return this.call('_capsule_shape_create', args); }
  _cylinder_shape_create(...args: readonly unknown[]): any { return this.call('_cylinder_shape_create', args); }
  _convex_polygon_shape_create(...args: readonly unknown[]): any { return this.call('_convex_polygon_shape_create', args); }
  _concave_polygon_shape_create(...args: readonly unknown[]): any { return this.call('_concave_polygon_shape_create', args); }
  _heightmap_shape_create(...args: readonly unknown[]): any { return this.call('_heightmap_shape_create', args); }
  _custom_shape_create(...args: readonly unknown[]): any { return this.call('_custom_shape_create', args); }
  _shape_set_data(...args: readonly unknown[]): any { return this.call('_shape_set_data', args); }
  _shape_set_custom_solver_bias(...args: readonly unknown[]): any { return this.call('_shape_set_custom_solver_bias', args); }
  _shape_set_margin(...args: readonly unknown[]): any { return this.call('_shape_set_margin', args); }
  _shape_get_margin(...args: readonly unknown[]): any { return this.call('_shape_get_margin', args); }
  _shape_get_type(...args: readonly unknown[]): any { return this.call('_shape_get_type', args); }
  _shape_get_data(...args: readonly unknown[]): any { return this.call('_shape_get_data', args); }
  _shape_get_custom_solver_bias(...args: readonly unknown[]): any { return this.call('_shape_get_custom_solver_bias', args); }
  _space_create(...args: readonly unknown[]): any { return this.call('_space_create', args); }
  _space_set_active(...args: readonly unknown[]): any { return this.call('_space_set_active', args); }
  _space_is_active(...args: readonly unknown[]): any { return this.call('_space_is_active', args); }
  _space_set_param(...args: readonly unknown[]): any { return this.call('_space_set_param', args); }
  _space_get_param(...args: readonly unknown[]): any { return this.call('_space_get_param', args); }
  _space_get_direct_state(...args: readonly unknown[]): any { return this.call('_space_get_direct_state', args); }
  _space_set_debug_contacts(...args: readonly unknown[]): any { return this.call('_space_set_debug_contacts', args); }
  _space_get_contacts(...args: readonly unknown[]): any { return this.call('_space_get_contacts', args); }
  _space_get_contact_count(...args: readonly unknown[]): any { return this.call('_space_get_contact_count', args); }
  _area_create(...args: readonly unknown[]): any { return this.call('_area_create', args); }
  _area_set_space(...args: readonly unknown[]): any { return this.call('_area_set_space', args); }
  _area_get_space(...args: readonly unknown[]): any { return this.call('_area_get_space', args); }
  _area_add_shape(...args: readonly unknown[]): any { return this.call('_area_add_shape', args); }
  _area_set_shape(...args: readonly unknown[]): any { return this.call('_area_set_shape', args); }
  _area_set_shape_transform(...args: readonly unknown[]): any { return this.call('_area_set_shape_transform', args); }
  _area_set_shape_disabled(...args: readonly unknown[]): any { return this.call('_area_set_shape_disabled', args); }
  _area_get_shape_count(...args: readonly unknown[]): any { return this.call('_area_get_shape_count', args); }
  _area_get_shape(...args: readonly unknown[]): any { return this.call('_area_get_shape', args); }
  _area_get_shape_transform(...args: readonly unknown[]): any { return this.call('_area_get_shape_transform', args); }
  _area_remove_shape(...args: readonly unknown[]): any { return this.call('_area_remove_shape', args); }
  _area_clear_shapes(...args: readonly unknown[]): any { return this.call('_area_clear_shapes', args); }
  _area_attach_object_instance_id(...args: readonly unknown[]): any { return this.call('_area_attach_object_instance_id', args); }
  _area_get_object_instance_id(...args: readonly unknown[]): any { return this.call('_area_get_object_instance_id', args); }
  _area_set_param(...args: readonly unknown[]): any { return this.call('_area_set_param', args); }
  _area_set_transform(...args: readonly unknown[]): any { return this.call('_area_set_transform', args); }
  _area_get_param(...args: readonly unknown[]): any { return this.call('_area_get_param', args); }
  _area_get_transform(...args: readonly unknown[]): any { return this.call('_area_get_transform', args); }
  _area_set_collision_layer(...args: readonly unknown[]): any { return this.call('_area_set_collision_layer', args); }
  _area_get_collision_layer(...args: readonly unknown[]): any { return this.call('_area_get_collision_layer', args); }
  _area_set_collision_mask(...args: readonly unknown[]): any { return this.call('_area_set_collision_mask', args); }
  _area_get_collision_mask(...args: readonly unknown[]): any { return this.call('_area_get_collision_mask', args); }
  _area_set_monitorable(...args: readonly unknown[]): any { return this.call('_area_set_monitorable', args); }
  _area_set_ray_pickable(...args: readonly unknown[]): any { return this.call('_area_set_ray_pickable', args); }
  _area_set_monitor_callback(...args: readonly unknown[]): any { return this.call('_area_set_monitor_callback', args); }
  _area_set_area_monitor_callback(...args: readonly unknown[]): any { return this.call('_area_set_area_monitor_callback', args); }
  _body_create(...args: readonly unknown[]): any { return this.call('_body_create', args); }
  _body_set_space(...args: readonly unknown[]): any { return this.call('_body_set_space', args); }
  _body_get_space(...args: readonly unknown[]): any { return this.call('_body_get_space', args); }
  _body_set_mode(...args: readonly unknown[]): any { return this.call('_body_set_mode', args); }
  _body_get_mode(...args: readonly unknown[]): any { return this.call('_body_get_mode', args); }
  _body_add_shape(...args: readonly unknown[]): any { return this.call('_body_add_shape', args); }
  _body_set_shape(...args: readonly unknown[]): any { return this.call('_body_set_shape', args); }
  _body_set_shape_transform(...args: readonly unknown[]): any { return this.call('_body_set_shape_transform', args); }
  _body_set_shape_disabled(...args: readonly unknown[]): any { return this.call('_body_set_shape_disabled', args); }
  _body_get_shape_count(...args: readonly unknown[]): any { return this.call('_body_get_shape_count', args); }
  _body_get_shape(...args: readonly unknown[]): any { return this.call('_body_get_shape', args); }
  _body_get_shape_transform(...args: readonly unknown[]): any { return this.call('_body_get_shape_transform', args); }
  _body_remove_shape(...args: readonly unknown[]): any { return this.call('_body_remove_shape', args); }
  _body_clear_shapes(...args: readonly unknown[]): any { return this.call('_body_clear_shapes', args); }
  _body_attach_object_instance_id(...args: readonly unknown[]): any { return this.call('_body_attach_object_instance_id', args); }
  _body_get_object_instance_id(...args: readonly unknown[]): any { return this.call('_body_get_object_instance_id', args); }
  _body_set_enable_continuous_collision_detection(...args: readonly unknown[]): any { return this.call('_body_set_enable_continuous_collision_detection', args); }
  _body_is_continuous_collision_detection_enabled(...args: readonly unknown[]): any { return this.call('_body_is_continuous_collision_detection_enabled', args); }
  _body_set_collision_layer(...args: readonly unknown[]): any { return this.call('_body_set_collision_layer', args); }
  _body_get_collision_layer(...args: readonly unknown[]): any { return this.call('_body_get_collision_layer', args); }
  _body_set_collision_mask(...args: readonly unknown[]): any { return this.call('_body_set_collision_mask', args); }
  _body_get_collision_mask(...args: readonly unknown[]): any { return this.call('_body_get_collision_mask', args); }
  _body_set_collision_priority(...args: readonly unknown[]): any { return this.call('_body_set_collision_priority', args); }
  _body_get_collision_priority(...args: readonly unknown[]): any { return this.call('_body_get_collision_priority', args); }
  _body_set_user_flags(...args: readonly unknown[]): any { return this.call('_body_set_user_flags', args); }
  _body_get_user_flags(...args: readonly unknown[]): any { return this.call('_body_get_user_flags', args); }
  _body_set_param(...args: readonly unknown[]): any { return this.call('_body_set_param', args); }
  _body_get_param(...args: readonly unknown[]): any { return this.call('_body_get_param', args); }
  _body_reset_mass_properties(...args: readonly unknown[]): any { return this.call('_body_reset_mass_properties', args); }
  _body_set_state(...args: readonly unknown[]): any { return this.call('_body_set_state', args); }
  _body_get_state(...args: readonly unknown[]): any { return this.call('_body_get_state', args); }
  _body_apply_central_impulse(...args: readonly unknown[]): any { return this.call('_body_apply_central_impulse', args); }
  _body_apply_impulse(...args: readonly unknown[]): any { return this.call('_body_apply_impulse', args); }
  _body_apply_torque_impulse(...args: readonly unknown[]): any { return this.call('_body_apply_torque_impulse', args); }
  _body_apply_central_force(...args: readonly unknown[]): any { return this.call('_body_apply_central_force', args); }
  _body_apply_force(...args: readonly unknown[]): any { return this.call('_body_apply_force', args); }
  _body_apply_torque(...args: readonly unknown[]): any { return this.call('_body_apply_torque', args); }
  _body_add_constant_central_force(...args: readonly unknown[]): any { return this.call('_body_add_constant_central_force', args); }
  _body_add_constant_force(...args: readonly unknown[]): any { return this.call('_body_add_constant_force', args); }
  _body_add_constant_torque(...args: readonly unknown[]): any { return this.call('_body_add_constant_torque', args); }
  _body_set_constant_force(...args: readonly unknown[]): any { return this.call('_body_set_constant_force', args); }
  _body_get_constant_force(...args: readonly unknown[]): any { return this.call('_body_get_constant_force', args); }
  _body_set_constant_torque(...args: readonly unknown[]): any { return this.call('_body_set_constant_torque', args); }
  _body_get_constant_torque(...args: readonly unknown[]): any { return this.call('_body_get_constant_torque', args); }
  _body_set_axis_velocity(...args: readonly unknown[]): any { return this.call('_body_set_axis_velocity', args); }
  _body_set_axis_lock(...args: readonly unknown[]): any { return this.call('_body_set_axis_lock', args); }
  _body_is_axis_locked(...args: readonly unknown[]): any { return this.call('_body_is_axis_locked', args); }
  _body_add_collision_exception(...args: readonly unknown[]): any { return this.call('_body_add_collision_exception', args); }
  _body_remove_collision_exception(...args: readonly unknown[]): any { return this.call('_body_remove_collision_exception', args); }
  _body_get_collision_exceptions(...args: readonly unknown[]): any { return this.call('_body_get_collision_exceptions', args); }
  _body_set_max_contacts_reported(...args: readonly unknown[]): any { return this.call('_body_set_max_contacts_reported', args); }
  _body_get_max_contacts_reported(...args: readonly unknown[]): any { return this.call('_body_get_max_contacts_reported', args); }
  _body_set_contacts_reported_depth_threshold(...args: readonly unknown[]): any { return this.call('_body_set_contacts_reported_depth_threshold', args); }
  _body_get_contacts_reported_depth_threshold(...args: readonly unknown[]): any { return this.call('_body_get_contacts_reported_depth_threshold', args); }
  _body_set_omit_force_integration(...args: readonly unknown[]): any { return this.call('_body_set_omit_force_integration', args); }
  _body_is_omitting_force_integration(...args: readonly unknown[]): any { return this.call('_body_is_omitting_force_integration', args); }
  _body_set_state_sync_callback(...args: readonly unknown[]): any { return this.call('_body_set_state_sync_callback', args); }
  _body_set_force_integration_callback(...args: readonly unknown[]): any { return this.call('_body_set_force_integration_callback', args); }
  _body_set_ray_pickable(...args: readonly unknown[]): any { return this.call('_body_set_ray_pickable', args); }
  _body_test_motion(...args: readonly unknown[]): any { return this.call('_body_test_motion', args); }
  _body_get_direct_state(...args: readonly unknown[]): any { return this.call('_body_get_direct_state', args); }
  _soft_body_create(...args: readonly unknown[]): any { return this.call('_soft_body_create', args); }
  _soft_body_update_rendering_server(...args: readonly unknown[]): any { return this.call('_soft_body_update_rendering_server', args); }
  _soft_body_set_space(...args: readonly unknown[]): any { return this.call('_soft_body_set_space', args); }
  _soft_body_get_space(...args: readonly unknown[]): any { return this.call('_soft_body_get_space', args); }
  _soft_body_set_ray_pickable(...args: readonly unknown[]): any { return this.call('_soft_body_set_ray_pickable', args); }
  _soft_body_set_collision_layer(...args: readonly unknown[]): any { return this.call('_soft_body_set_collision_layer', args); }
  _soft_body_get_collision_layer(...args: readonly unknown[]): any { return this.call('_soft_body_get_collision_layer', args); }
  _soft_body_set_collision_mask(...args: readonly unknown[]): any { return this.call('_soft_body_set_collision_mask', args); }
  _soft_body_get_collision_mask(...args: readonly unknown[]): any { return this.call('_soft_body_get_collision_mask', args); }
  _soft_body_add_collision_exception(...args: readonly unknown[]): any { return this.call('_soft_body_add_collision_exception', args); }
  _soft_body_remove_collision_exception(...args: readonly unknown[]): any { return this.call('_soft_body_remove_collision_exception', args); }
  _soft_body_get_collision_exceptions(...args: readonly unknown[]): any { return this.call('_soft_body_get_collision_exceptions', args); }
  _soft_body_set_state(...args: readonly unknown[]): any { return this.call('_soft_body_set_state', args); }
  _soft_body_get_state(...args: readonly unknown[]): any { return this.call('_soft_body_get_state', args); }
  _soft_body_set_transform(...args: readonly unknown[]): any { return this.call('_soft_body_set_transform', args); }
  _soft_body_set_simulation_precision(...args: readonly unknown[]): any { return this.call('_soft_body_set_simulation_precision', args); }
  _soft_body_get_simulation_precision(...args: readonly unknown[]): any { return this.call('_soft_body_get_simulation_precision', args); }
  _soft_body_set_total_mass(...args: readonly unknown[]): any { return this.call('_soft_body_set_total_mass', args); }
  _soft_body_get_total_mass(...args: readonly unknown[]): any { return this.call('_soft_body_get_total_mass', args); }
  _soft_body_set_linear_stiffness(...args: readonly unknown[]): any { return this.call('_soft_body_set_linear_stiffness', args); }
  _soft_body_get_linear_stiffness(...args: readonly unknown[]): any { return this.call('_soft_body_get_linear_stiffness', args); }
  _soft_body_set_shrinking_factor(...args: readonly unknown[]): any { return this.call('_soft_body_set_shrinking_factor', args); }
  _soft_body_get_shrinking_factor(...args: readonly unknown[]): any { return this.call('_soft_body_get_shrinking_factor', args); }
  _soft_body_set_pressure_coefficient(...args: readonly unknown[]): any { return this.call('_soft_body_set_pressure_coefficient', args); }
  _soft_body_get_pressure_coefficient(...args: readonly unknown[]): any { return this.call('_soft_body_get_pressure_coefficient', args); }
  _soft_body_set_damping_coefficient(...args: readonly unknown[]): any { return this.call('_soft_body_set_damping_coefficient', args); }
  _soft_body_get_damping_coefficient(...args: readonly unknown[]): any { return this.call('_soft_body_get_damping_coefficient', args); }
  _soft_body_set_drag_coefficient(...args: readonly unknown[]): any { return this.call('_soft_body_set_drag_coefficient', args); }
  _soft_body_get_drag_coefficient(...args: readonly unknown[]): any { return this.call('_soft_body_get_drag_coefficient', args); }
  _soft_body_set_mesh(...args: readonly unknown[]): any { return this.call('_soft_body_set_mesh', args); }
  _soft_body_get_bounds(...args: readonly unknown[]): any { return this.call('_soft_body_get_bounds', args); }
  _soft_body_move_point(...args: readonly unknown[]): any { return this.call('_soft_body_move_point', args); }
  _soft_body_get_point_global_position(...args: readonly unknown[]): any { return this.call('_soft_body_get_point_global_position', args); }
  _soft_body_remove_all_pinned_points(...args: readonly unknown[]): any { return this.call('_soft_body_remove_all_pinned_points', args); }
  _soft_body_pin_point(...args: readonly unknown[]): any { return this.call('_soft_body_pin_point', args); }
  _soft_body_is_point_pinned(...args: readonly unknown[]): any { return this.call('_soft_body_is_point_pinned', args); }
  _soft_body_apply_point_impulse(...args: readonly unknown[]): any { return this.call('_soft_body_apply_point_impulse', args); }
  _soft_body_apply_point_force(...args: readonly unknown[]): any { return this.call('_soft_body_apply_point_force', args); }
  _soft_body_apply_central_impulse(...args: readonly unknown[]): any { return this.call('_soft_body_apply_central_impulse', args); }
  _soft_body_apply_central_force(...args: readonly unknown[]): any { return this.call('_soft_body_apply_central_force', args); }
  _joint_create(...args: readonly unknown[]): any { return this.call('_joint_create', args); }
  _joint_clear(...args: readonly unknown[]): any { return this.call('_joint_clear', args); }
  _joint_make_pin(...args: readonly unknown[]): any { return this.call('_joint_make_pin', args); }
  _pin_joint_set_param(...args: readonly unknown[]): any { return this.call('_pin_joint_set_param', args); }
  _pin_joint_get_param(...args: readonly unknown[]): any { return this.call('_pin_joint_get_param', args); }
  _pin_joint_set_local_a(...args: readonly unknown[]): any { return this.call('_pin_joint_set_local_a', args); }
  _pin_joint_get_local_a(...args: readonly unknown[]): any { return this.call('_pin_joint_get_local_a', args); }
  _pin_joint_set_local_b(...args: readonly unknown[]): any { return this.call('_pin_joint_set_local_b', args); }
  _pin_joint_get_local_b(...args: readonly unknown[]): any { return this.call('_pin_joint_get_local_b', args); }
  _joint_make_hinge(...args: readonly unknown[]): any { return this.call('_joint_make_hinge', args); }
  _joint_make_hinge_simple(...args: readonly unknown[]): any { return this.call('_joint_make_hinge_simple', args); }
  _hinge_joint_set_param(...args: readonly unknown[]): any { return this.call('_hinge_joint_set_param', args); }
  _hinge_joint_get_param(...args: readonly unknown[]): any { return this.call('_hinge_joint_get_param', args); }
  _hinge_joint_set_flag(...args: readonly unknown[]): any { return this.call('_hinge_joint_set_flag', args); }
  _hinge_joint_get_flag(...args: readonly unknown[]): any { return this.call('_hinge_joint_get_flag', args); }
  _joint_make_slider(...args: readonly unknown[]): any { return this.call('_joint_make_slider', args); }
  _slider_joint_set_param(...args: readonly unknown[]): any { return this.call('_slider_joint_set_param', args); }
  _slider_joint_get_param(...args: readonly unknown[]): any { return this.call('_slider_joint_get_param', args); }
  _joint_make_cone_twist(...args: readonly unknown[]): any { return this.call('_joint_make_cone_twist', args); }
  _cone_twist_joint_set_param(...args: readonly unknown[]): any { return this.call('_cone_twist_joint_set_param', args); }
  _cone_twist_joint_get_param(...args: readonly unknown[]): any { return this.call('_cone_twist_joint_get_param', args); }
  _joint_make_generic_6dof(...args: readonly unknown[]): any { return this.call('_joint_make_generic_6dof', args); }
  _generic_6dof_joint_set_param(...args: readonly unknown[]): any { return this.call('_generic_6dof_joint_set_param', args); }
  _generic_6dof_joint_get_param(...args: readonly unknown[]): any { return this.call('_generic_6dof_joint_get_param', args); }
  _generic_6dof_joint_set_flag(...args: readonly unknown[]): any { return this.call('_generic_6dof_joint_set_flag', args); }
  _generic_6dof_joint_get_flag(...args: readonly unknown[]): any { return this.call('_generic_6dof_joint_get_flag', args); }
  _joint_get_type(...args: readonly unknown[]): any { return this.call('_joint_get_type', args); }
  _joint_set_solver_priority(...args: readonly unknown[]): any { return this.call('_joint_set_solver_priority', args); }
  _joint_get_solver_priority(...args: readonly unknown[]): any { return this.call('_joint_get_solver_priority', args); }
  _joint_disable_collisions_between_bodies(...args: readonly unknown[]): any { return this.call('_joint_disable_collisions_between_bodies', args); }
  _joint_is_disabled_collisions_between_bodies(...args: readonly unknown[]): any { return this.call('_joint_is_disabled_collisions_between_bodies', args); }
  _free_rid(...args: readonly unknown[]): any { return this.call('_free_rid', args); }
  _set_active(...args: readonly unknown[]): any { return this.call('_set_active', args); }
  _init(...args: readonly unknown[]): any { return this.call('_init', args); }
  _step(...args: readonly unknown[]): any { return this.call('_step', args); }
  _sync(...args: readonly unknown[]): any { return this.call('_sync', args); }
  _flush_queries(...args: readonly unknown[]): any { return this.call('_flush_queries', args); }
  _end_sync(...args: readonly unknown[]): any { return this.call('_end_sync', args); }
  _finish(...args: readonly unknown[]): any { return this.call('_finish', args); }
  _is_flushing_queries(...args: readonly unknown[]): any { return this.call('_is_flushing_queries', args); }
  _get_process_info(...args: readonly unknown[]): any { return this.call('_get_process_info', args); }
  body_test_motion_is_excluding_body(...args: readonly unknown[]): any { return this.call('body_test_motion_is_excluding_body', args); }
  body_test_motion_is_excluding_object(...args: readonly unknown[]): any { return this.call('body_test_motion_is_excluding_object', args); }
}

export function createGodotPhysicsServer3DExtension(carrier: GodotPhysicsServer3DExtensionCarrier): GodotPhysicsServer3DExtension { return new GodotPhysicsServer3DExtension(carrier); }
