import { godotRidGetId, type GodotRid } from './gdscript-builtins';
import { registerGodotObjectIdentity } from './object';

export type GodotRenderingCommandLane = 'resource' | 'transfer' | 'compute' | 'draw' | 'present';
export type GodotRenderingCommandStatus = 'queued' | 'executing' | 'complete' | 'failed' | 'cancelled';
export interface GodotRenderingQueuedCommand { readonly id: number; readonly name: string; readonly lane: GodotRenderingCommandLane; readonly frame: number; readonly priority: number; readonly resources: readonly GodotRid[]; readonly after: readonly number[]; readonly status: GodotRenderingCommandStatus; readonly error: unknown | null; readonly generation: number }
export interface GodotRenderingCommandDescriptor { readonly name: string; readonly lane: GodotRenderingCommandLane; readonly priority?: number; readonly resources?: readonly GodotRid[]; readonly after?: readonly number[]; readonly execute: () => void | Promise<void> }
export interface GodotRenderingCommandFrameResult { readonly frame: number; readonly completed: readonly number[]; readonly failed: readonly { id: number; error: unknown }[]; readonly cancelled: readonly number[]; readonly barriers: number }
export interface GodotRenderingCommandQueueSnapshot { readonly frame: number; readonly commands: readonly GodotRenderingQueuedCommand[]; readonly queued: number; readonly executing: number; readonly complete: number; readonly failed: number; readonly cancelled: number; readonly flushes: number; readonly generation: number; readonly lastFrame: GodotRenderingCommandFrameResult | null }
interface Entry { id: number; name: string; lane: GodotRenderingCommandLane; frame: number; priority: number; resources: GodotRid[]; after: number[]; status: GodotRenderingCommandStatus; error: unknown | null; generation: number; execute: () => void | Promise<void>; order: number }
const LANES: readonly GodotRenderingCommandLane[] = Object.freeze(['resource', 'transfer', 'compute', 'draw', 'present']);
function integer(value: unknown, member: string, minimum = 0): number { const result = Number(value); if (!Number.isSafeInteger(result) || result < minimum) throw new RangeError(`godot-compat: RenderingCommandQueue.${member} requires integer >= ${minimum}.`); return result; }
function finite(value: unknown, member: string): number { const result = Number(value); if (!Number.isFinite(result)) throw new RangeError(`godot-compat: RenderingCommandQueue.${member} requires finite value.`); return result; }
function name(value: unknown): string { const result = String(value); if (result.length === 0) throw new RangeError('godot-compat: rendering command requires nonempty name.'); return result; }
function lane(value: unknown): GodotRenderingCommandLane { if (!LANES.includes(value as GodotRenderingCommandLane)) throw new TypeError(`godot-compat: unknown rendering command lane ${String(value)}.`); return value as GodotRenderingCommandLane; }
function rid(value: unknown): GodotRid { if (value === null || typeof value !== 'object') throw new TypeError('godot-compat: rendering command resource requires RID.'); godotRidGetId(value); return value as GodotRid; }
function snapshot(entry: Entry): GodotRenderingQueuedCommand { return Object.freeze({ id: entry.id, name: entry.name, lane: entry.lane, frame: entry.frame, priority: entry.priority, resources: Object.freeze([...entry.resources]), after: Object.freeze([...entry.after]), status: entry.status, error: entry.error, generation: entry.generation }); }

export class GodotRenderingCommandQueueRuntime {
  public readonly __godotClass = 'RenderingCommandQueueRuntime'; private readonly commands = new Map<number, Entry>(); private readonly watchers = new Set<(snapshot: GodotRenderingCommandQueueSnapshot) => void>();
  private frameValue = 0; private nextId = 1; private nextOrder = 0; private generationValue = 0; private flushes = 0; private flushing = false; private stopOnErrorValue = true; private historyLimitValue = 2048;
  private lastFrame: GodotRenderingCommandFrameResult | null = null;
  public constructor() { registerGodotObjectIdentity(this, 'RenderingCommandQueueRuntime'); }
  public enqueue(value: GodotRenderingCommandDescriptor): number { if (typeof value.execute !== 'function') throw new TypeError('godot-compat: rendering command requires execute Callable.'); const id = this.nextId++; const entry: Entry = { id, name: name(value.name), lane: lane(value.lane), frame: this.frameValue, priority: finite(value.priority ?? 0, 'priority'), resources: (value.resources ?? []).map(rid), after: (value.after ?? []).map((one) => integer(one, 'after', 1)), status: 'queued', error: null, generation: 1, execute: value.execute, order: this.nextOrder++ }; for (const dependency of entry.after) if (!this.commands.has(dependency)) throw new Error(`godot-compat: rendering command ${id} depends on unknown command ${dependency}.`); this.commands.set(id, entry); this.assertAcyclic(); this.generationValue += 1; this.publish(); return id; }
  public cancel(idValue: unknown, includeDependents = false): boolean { const id = integer(idValue, 'id', 1), entry = this.commands.get(id); if (entry === undefined || entry.status !== 'queued') return false; entry.status = 'cancelled'; entry.generation += 1; if (includeDependents) for (const dependent of this.commands.values()) if (dependent.after.includes(id)) this.cancel(dependent.id, true); this.publish(); return true; }
  private assertAcyclic(): void { const visiting = new Set<number>(), visited = new Set<number>(); const visit = (id: number) => { if (visiting.has(id)) throw new Error(`godot-compat: rendering command dependency cycle contains ${id}.`); if (visited.has(id)) return; visiting.add(id); for (const dependency of this.commands.get(id)?.after ?? []) visit(dependency); visiting.delete(id); visited.add(id); }; for (const id of this.commands.keys()) visit(id); }
  private ordered(frame: number): Entry[] { const selected = new Map([...this.commands.values()].filter((entry) => entry.frame <= frame && entry.status === 'queued').map((entry) => [entry.id, entry])), remaining = new Map(selected), output: Entry[] = [], laneOrder = new Map(LANES.map((one, index) => [one, index])); while (remaining.size > 0) { const ready = [...remaining.values()].filter((entry) => entry.after.every((dependency) => !remaining.has(dependency))).sort((left, right) => laneOrder.get(left.lane)! - laneOrder.get(right.lane)! || right.priority - left.priority || left.order - right.order); if (ready.length === 0) throw new Error('godot-compat: rendering command dependency cycle.'); for (const entry of ready) { output.push(entry); remaining.delete(entry.id); } } return output; }
  private resourceConflict(left: Entry, right: Entry): boolean { const resources = new Set(left.resources.map(godotRidGetId)); return right.resources.some((resource) => resources.has(godotRidGetId(resource))); }
  public async flush(frameValue: unknown): Promise<GodotRenderingCommandFrameResult> { const frame = integer(frameValue, 'frame'); if (frame < this.frameValue) throw new RangeError('godot-compat: rendering command frame cannot move backwards.'); if (this.flushing) throw new Error('godot-compat: rendering command queue already flushing.'); this.frameValue = frame; this.flushing = true; const completed: number[] = [], failed: Array<{ id: number; error: unknown }> = [], cancelled: number[] = []; let barriers = 0, previous: Entry | null = null; try { for (const entry of this.ordered(frame)) { if (entry.after.some((dependency) => { const state = this.commands.get(dependency)?.status; return state === 'failed' || state === 'cancelled'; })) { entry.status = 'cancelled'; cancelled.push(entry.id); continue; } if (previous !== null && (previous.lane !== entry.lane || this.resourceConflict(previous, entry))) barriers += 1; entry.status = 'executing'; entry.generation += 1; this.publish(); try { await entry.execute(); entry.status = 'complete'; completed.push(entry.id); } catch (error) { entry.status = 'failed'; entry.error = error; failed.push(Object.freeze({ id: entry.id, error })); if (this.stopOnErrorValue) { for (const pending of this.commands.values()) if (pending.status === 'queued' && pending.after.includes(entry.id)) { pending.status = 'cancelled'; cancelled.push(pending.id); } break; } } finally { entry.generation += 1; } previous = entry; } this.flushes += 1; this.lastFrame = Object.freeze({ frame, completed: Object.freeze(completed), failed: Object.freeze(failed), cancelled: Object.freeze(cancelled), barriers }); this.trim(); this.publish(); return this.lastFrame; } finally { this.flushing = false; } }
  private trim(): void { const terminal = [...this.commands.values()].filter((entry) => entry.status === 'complete' || entry.status === 'failed' || entry.status === 'cancelled').sort((left, right) => left.order - right.order); const remove = terminal.length - this.historyLimitValue; if (remove <= 0) return; for (let index = 0; index < remove; index += 1) { const entry = terminal[index]!; if (![...this.commands.values()].some((candidate) => candidate.status === 'queued' && candidate.after.includes(entry.id))) this.commands.delete(entry.id); } }
  public beginFrame(frameValue: unknown): void { const frame = integer(frameValue, 'frame'); if (frame < this.frameValue) throw new RangeError('godot-compat: rendering command frame cannot move backwards.'); this.frameValue = frame; }
  public setStopOnError(value: unknown): void { if (typeof value !== 'boolean') throw new TypeError('godot-compat: RenderingCommandQueue.stop_on_error requires bool.'); this.stopOnErrorValue = value; }
  public setHistoryLimit(value: unknown): void { this.historyLimitValue = integer(value, 'history_limit'); this.trim(); }
  public getCommand(idValue: unknown): GodotRenderingQueuedCommand | null { const entry = this.commands.get(integer(idValue, 'id', 1)); return entry === undefined ? null : snapshot(entry); }
  public getSnapshot(): GodotRenderingCommandQueueSnapshot { const commands = [...this.commands.values()].sort((left, right) => left.order - right.order).map(snapshot); return Object.freeze({ frame: this.frameValue, commands: Object.freeze(commands), queued: commands.filter((entry) => entry.status === 'queued').length, executing: commands.filter((entry) => entry.status === 'executing').length, complete: commands.filter((entry) => entry.status === 'complete').length, failed: commands.filter((entry) => entry.status === 'failed').length, cancelled: commands.filter((entry) => entry.status === 'cancelled').length, flushes: this.flushes, generation: this.generationValue, lastFrame: this.lastFrame }); }
  public watch(watcher: (snapshot: GodotRenderingCommandQueueSnapshot) => void): () => void { this.watchers.add(watcher); watcher(this.getSnapshot()); return () => this.watchers.delete(watcher); }
  private publish(): void { const value = this.getSnapshot(); for (const watcher of this.watchers) watcher(value); }
  public clear(): void { if (this.flushing) throw new Error('godot-compat: cannot clear rendering commands during flush.'); this.commands.clear(); this.lastFrame = null; this.generationValue += 1; this.publish(); }
  public dispose(): void { this.clear(); this.watchers.clear(); }
}

export function createGodotRenderingCommandQueueRuntime(): GodotRenderingCommandQueueRuntime { return new GodotRenderingCommandQueueRuntime(); }
