/**
 * The project directories a tool may commit generated bytes into, and the one
 * normalizer every writer validates a path with.
 *
 * A project has two of them, and the difference is what SHIPS:
 *
 *   - `public/`     — game assets. Exported, served at a root-relative URL,
 *                     loaded by the game's own source.
 *   - `references/` — reference material: moodboards, style plates, generated
 *                     stills and clips an author or an agent looks at while
 *                     building. Ordinary files, indexed by the editor's Content
 *                     panel like any other media, and NOT exported — the
 *                     project's own build copies `publicDir` and nothing else.
 *
 * This lives in the SDK rather than beside one writer because the rule has more
 * than one enforcer: the editor host's atomic project-output writer, and every
 * registered provider boundary that takes an `outputDirectory` from a caller.
 * Two copies of "must be under public/" is how a reference output becomes
 * writable through one door and refused at the next.
 */

/** The writable output roots, in the order a chooser should offer them. */
export const PROJECT_OUTPUT_ROOTS = ['public', 'references'] as const;

export type ProjectOutputRoot = (typeof PROJECT_OUTPUT_ROOTS)[number];

/** Human-readable list for an error message: `public/` or `references/`. */
function rootList(): string {
  return PROJECT_OUTPUT_ROOTS.map((root) => `${root}/`).join(' or ');
}

/** POSIX-normalized, `./`-stripped, trailing-slash-stripped. */
function normalizeSlashes(path: string): string {
  const slashed = path.replaceAll('\\', '/');
  const segments: string[] = [];
  for (const segment of slashed.split('/')) {
    if (segment === '' || segment === '.') continue;
    segments.push(segment);
  }
  return segments.join('/');
}

/** The root `path` sits under, or `undefined` when it sits under none. */
export function projectOutputRootOf(path: string): ProjectOutputRoot | undefined {
  const normalized = normalizeSlashes(path);
  return PROJECT_OUTPUT_ROOTS.find(
    (root) => normalized === root || normalized.startsWith(`${root}/`),
  );
}

/**
 * Validate and normalize a project-relative output path.
 *
 * Throws — with a message naming BOTH roots, because the common mistake is
 * knowing about one of them — for an absolute path, an escape, a bare root
 * with no file under it, or anything outside the roots above. `subject` names
 * what is being validated in that message (`Generated output path`, `Fal
 * outputDirectory`, …).
 */
export function normalizeProjectOutputPath(
  path: string,
  subject = 'Generated output path',
): string {
  const normalized = normalizeSlashes(path);
  const escapes = normalized.split('/').includes('..');
  const root = projectOutputRootOf(normalized);
  if (path.startsWith('/') || escapes || root === undefined || normalized === root) {
    throw new Error(
      `${subject} ${JSON.stringify(path)} is invalid; it must be a project-relative path under ${rootList()}.`,
    );
  }
  return normalized;
}
