// Bundles the workbench's own opening module (packages/cyclotron/workbench/src/opening.ts) into
// opening.js for index.html, with three small stand-ins for the Code-OSS modules it imports, so
// the preview runs the product's exact code in a plain browser tab, from file:// too.
//
//   node design/opening/preview/build.mjs     (run from a checkout with node_modules: it
//                                              resolves esbuild from the current directory)
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');
const esbuild = createRequire(join(process.cwd(), 'package.json'))('esbuild');
const shims = {
	'base/browser/dom.js': String.raw`
		const make = (ns) => (description, attrs, ...children) => {
			const [, tag = 'div', , id, classes = ''] = /^([\w-]+)?(#([\w-]+))?((\.[\w-]+)*)$/.exec(description) ?? [];
			const node = ns ? document.createElementNS(ns, tag) : document.createElement(tag);
			if (id) node.id = id;
			if (classes) node.setAttribute('class', classes.replace(/\./g, ' ').trim());
			for (const [name, value] of Object.entries(attrs ?? {})) if (value !== undefined) node.setAttribute(name, value);
			node.append(...children);
			return node;
		};
		export const $ = make(null);
		$.SVG = make('http://www.w3.org/2000/svg');`,
	'base/browser/window.js': 'export const mainWindow = window;',
	'nls.js': String.raw`export const localize = (key, message, ...args) => message.replace(/\{(\d+)\}/g, (_, i) => String(args[i]));`,
};
await esbuild.build({
	// Paths in the bundle's comments are relative to the repository, whichever checkout builds it.
	absWorkingDir: repo,
	entryPoints: [join(repo, 'packages/cyclotron/workbench/src/opening.ts')],
	bundle: true,
	format: 'iife',
	globalName: 'VolterOpening',
	outfile: join(here, 'opening.js'),
	banner: { js: '// GENERATED by design/opening/preview/build.mjs from packages/cyclotron/workbench/src/opening.ts. Do not edit.' },
	plugins: [{
		name: 'code-oss-stand-ins',
		setup(build) {
			build.onResolve({ filter: /(base\/browser\/(dom|window)|\/nls)\.js$/ }, (args) => ({ path: Object.keys(shims).find((key) => args.path.endsWith(key)), namespace: 'shim' }));
			build.onLoad({ filter: /.*/, namespace: 'shim' }, (args) => ({ contents: shims[args.path], loader: 'js' }));
		},
	}],
});
console.log('wrote', join(here, 'opening.js'));
