// GENERATED by design/opening/preview/build.mjs from packages/cyclotron/workbench/src/opening.ts. Do not edit.
var VolterOpening = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // ../editor-opening/packages/cyclotron/workbench/src/opening.ts
  var opening_exports = {};
  __export(opening_exports, {
    mountOpening: () => mountOpening,
    pullSetting: () => pullSetting
  });

  // shim:base/browser/dom.js
  var make = (ns) => (description, attrs, ...children) => {
    const [, tag = "div", , id, classes = ""] = /^([\w-]+)?(#([\w-]+))?((\.[\w-]+)*)$/.exec(description) ?? [];
    const node = ns ? document.createElementNS(ns, tag) : document.createElement(tag);
    if (id) node.id = id;
    if (classes) node.setAttribute("class", classes.replace(/\./g, " ").trim());
    for (const [name, value] of Object.entries(attrs ?? {})) if (value !== void 0) node.setAttribute(name, value);
    node.append(...children);
    return node;
  };
  var $ = make(null);
  $.SVG = make("http://www.w3.org/2000/svg");

  // shim:base/browser/window.js
  var mainWindow = window;

  // shim:nls.js
  var localize = (key, message, ...args) => message.replace(/\{(\d+)\}/g, (_, i) => String(args[i]));

  // ../editor-opening/packages/cyclotron/workbench/src/opening.ts
  var STORAGE_KEY = "volter.cyclotron.opening";
  function pullSetting(settings) {
    let seen = [];
    let last;
    try {
      const memory = JSON.parse(mainWindow.localStorage.getItem(STORAGE_KEY) ?? "{}");
      if (memory && typeof memory === "object") {
        const record = memory;
        if (Array.isArray(record.seen)) {
          seen = record.seen.filter((id) => typeof id === "string");
        }
        if (typeof record.last === "string") {
          last = record.last;
        }
      }
    } catch {
    }
    const fresh = settings.find((candidate) => !seen.includes(candidate.id));
    const setting = fresh ?? settings[(settings.findIndex((candidate) => candidate.id === last) + 1) % settings.length];
    try {
      mainWindow.localStorage.setItem(STORAGE_KEY, JSON.stringify({ seen: fresh ? [...seen, fresh.id] : seen, last: setting.id }));
    } catch {
    }
    return { setting, isNew: fresh !== void 0 };
  }
  var SILHOUETTE = "M120.6 7.1l2.5 0 1.8 .8 .2 .5 0 11.2 2.3 .8 .2-1.5 .8-.8 2-.5 2.2 .3 1 .5 .5 .7 0 4 1.8 1.8 .7 1.5 0 2 4 2 2.5 1.7 2.5 2.8 1 2.2 1 3.5 .3 2.8-1.3 3.2 0 6-1 1.8 2.5 2 0 19.2 4 1.3 6 2.7 7 4.5 4.5 5 1.5 3.3 1.3 3.2 .2 5-2.5 7-1.5 1.8 .3 4.7 1.2 2 2.3 5.5 .2 5-2.5 7-4.2 5-5 3.8-7 3.5-2.3 .7 0 3.8-1.7 1.5 1.7 1.5 0 4.2-3.5 3 0 10-1.5 1.8 0 6-1.7 3.2-2.3 1.8 0 6.5 .5 .5 3.8 1.2 2.5 2 0 10.5-3 2.8 5 2 2.5 2 0 10.2-3.8 3.3-9.7 6-1.5 .2-10-3.7-2.8-2.3-.2-7.7-2.5 .5-5 0-.3 6-4.2 3.5-9.8 6-.5 0-10.5-4-2.5-2 0-10.5 3-2.8-5-2-2.5-2 0-10.2 3-2.8 8.3-5 0-8.2-2.5-2.3-1.5-2.7 0-6.3-1-2 0-2-.5-1 0-8.5-1-.7-6.8-2.5-2.2-2 0-9.5-7.3-4.8-3-3.2-1-1.3-3-6.7-.2-5 2.5-7 1.5-1.8-.3-4.7-1-1.5-2.5-6-.2-5 2.5-7 4.2-5 5-3.8 7-3.5 5.8-2 0-22.7 1.5-1.5 0-5-1-2-.3-2.8 1.8-5.7 2.7-3.5 2-1.5 4.8-2.5 0-2 .7-1.3 0-8 .5-.5 1.5-.5 2.3 0 1.5 .5 .5 .5 .2 3.8 3.5-1 4.5-.5 0-11z";
  var CHARGE = 450;
  var FLIP = 1500;
  var FLIP_END = 1950;
  var SETTLE = 2500;
  var PRINT_AT = FLIP_END - 150;
  var PRINT = 1500;
  var STARS_AT = PRINT_AT + PRINT + 520;
  var STAR_STEP = 190;
  var NAME_AT = STARS_AT + 5 * STAR_STEP + 60;
  var UNDER_AT = STARS_AT + 5 * STAR_STEP + 300;
  var SETTLED_MS = UNDER_AT + 900;
  var ART_WAIT_MS = 400;
  var BACK_SCAN = 392;
  var clamp = (x, low = 0, high = 1) => Math.max(low, Math.min(high, x));
  var ease = (x) => {
    const k = clamp(x);
    return k * k * (3 - 2 * k);
  };
  var outBack = (x) => {
    const k = clamp(x);
    const c = 1.7;
    return 1 + (c + 1) * Math.pow(k - 1, 3) + c * Math.pow(k - 1, 2);
  };
  var outExpo = (x) => x >= 1 ? 1 : 1 - Math.pow(2, -10 * clamp(x));
  var inCubic = (x) => clamp(x) ** 3;
  var random = /* @__PURE__ */ (() => {
    let seed = 7;
    return () => (seed = seed * 16807 % 2147483647) / 2147483647;
  })();
  var INBOUND = Array.from({ length: 70 }, () => ({ a: random() * Math.PI * 2, r: 260 + random() * 340, start: CHARGE + random() * 900, life: 380 + random() * 260, size: 0.8 + random() * 1.8 }));
  var BURST = Array.from({ length: 110 }, () => ({ a: random() * Math.PI * 2, v: 0.25 + random() * 0.75, life: 700 + random() * 900, size: 0.8 + random() * 2.4, lime: random() < 0.7 }));
  var STAR_SPARK = Array.from({ length: 14 }, (_, i) => ({ a: i / 14 * Math.PI * 2 + random() * 0.3, v: 0.6 + random() * 0.6 }));
  var GLINTS = Array.from({ length: 16 }, () => ({ x: random(), y: random(), period: 2200 + random() * 2600, phase: random() * 4e3 }));
  function mountOpening(host, setting, isNew, firstLine, at) {
    const halo = $(".volter-opening-halo");
    const rays = $(".volter-opening-rays");
    const ring = $(".volter-opening-ring");
    const sparks = $("canvas.volter-opening-sparks");
    const silhouette = $.SVG(
      "svg",
      { viewBox: "0 0 240 240", "aria-hidden": "true" },
      $.SVG("path", { d: SILHOUETTE, fill: "rgba(220,213,233,.07)", stroke: "none" }),
      $.SVG("path", { d: SILHOUETTE, fill: "none", stroke: "rgba(228,240,156,.85)", "stroke-width": "1.4", "stroke-linejoin": "round" })
    );
    const backFill = $(".volter-opening-back-fill");
    const backScan = $(".volter-opening-back-scan");
    const edge = $(".volter-opening-back-edge");
    const back = $(
      ".volter-opening-face.volter-opening-back",
      void 0,
      $(".volter-opening-back-inner"),
      silhouette,
      $(".volter-opening-mark", void 0, "CYCLOTRON"),
      backFill,
      backScan,
      edge
    );
    const art = $("img.volter-opening-art", { alt: "" });
    art.src = setting.art;
    const stars = Array.from({ length: 5 }, () => $("b", void 0, "\u2605"));
    const name = $(".volter-opening-name", void 0, setting.name);
    const badge = isNew ? $(".volter-opening-new", void 0, localize("volterOpeningNew", "New")) : void 0;
    const id = $(".volter-opening-id", void 0, ...badge ? [badge] : [], $(".volter-opening-stars", void 0, ...stars), name);
    const etch = $(".volter-opening-etch");
    const holo = $(".volter-opening-holo");
    const glare = $(".volter-opening-glare");
    const sweep = $(".volter-opening-sweep");
    const rim = $(".volter-opening-rim");
    const front = $(".volter-opening-face.volter-opening-front", void 0, art, id, etch, $(".volter-opening-keyline"), holo, glare, sweep, rim);
    const card = $(".volter-opening-card", void 0, back, front);
    const stage = $(".volter-opening-stage", void 0, card);
    const state = $(".volter-opening-state", void 0, firstLine);
    const under = $(".volter-opening-under", void 0, $(".volter-opening-rail"), state);
    const flash = $(".volter-opening-flash");
    const root = $(
      ".volter-opening",
      void 0,
      $(".volter-opening-fx", void 0, halo, rays, ring, sparks),
      stage,
      under,
      $(".volter-opening-fx", void 0, flash)
    );
    host.appendChild(root);
    const context = sparks.getContext("2d");
    let width = 0, height = 0;
    function frame(t) {
      const box = root.getBoundingClientRect();
      const stageBox = stage.getBoundingClientRect();
      const cx = stageBox.left - box.left + stageBox.width / 2, cy = stageBox.top - box.top + stageBox.height / 2;
      const starBursts = [];
      stars.forEach((star, i) => {
        const k = (t - (STARS_AT + i * STAR_STEP)) / 320;
        if (i < setting.stars && k >= 0 && k < 2.2) {
          const r = star.getBoundingClientRect();
          starBursts.push({ x: r.left - box.left + r.width / 2, y: r.top - box.top + r.height / 2, k: k / 2.2 });
        }
      });
      if (box.width !== width || box.height !== height) {
        width = box.width;
        height = box.height;
        const dpr = Math.min(2, mainWindow.devicePixelRatio || 1);
        sparks.width = Math.round(width * dpr);
        sparks.height = Math.round(height * dpr);
        context?.setTransform(dpr, 0, 0, dpr, 0, 0);
      }
      const rise = outExpo(t / 650);
      const charge = clamp((t - CHARGE) / (FLIP - CHARGE));
      const shake = t < FLIP ? 0.4 + 5.5 * inCubic(charge) : 0;
      const sx = Math.sin(t * 0.083) * shake + Math.sin(t * 0.131) * shake * 0.5;
      const sy = Math.cos(t * 0.097) * shake * 0.6;
      const flip = ease((t - FLIP) / (FLIP_END - FLIP));
      const swell = Math.sin(Math.PI * clamp((t - FLIP) / (FLIP_END - FLIP))) * 0.16;
      const settle = outBack((t - FLIP_END) / (SETTLE - FLIP_END));
      const idle = clamp((t - SETTLE) / 800);
      const tiltX = idle * (Math.sin(t / 1900) * 5) + (t < FLIP ? -6 * (1 - rise) : 0);
      const tiltY = idle * (Math.sin(t / 2600 + 1) * 8);
      const floatY = idle * Math.sin(t / 1500) * 5;
      const angle = 180 + flip * 180 + (1 - settle) * (t > FLIP_END ? -8 : 0);
      const scale = (0.86 + 0.14 * rise) * (1 + swell) * (t > FLIP_END ? 1 + (1 - settle) * 0.05 : 1) * (1 + (t < FLIP ? charge * 0.03 : 0));
      card.style.transform = `translate3d(${sx.toFixed(2)}px,${(sy + (1 - rise) * 70 + floatY).toFixed(2)}px,0) rotateX(${tiltX.toFixed(2)}deg) rotateY(${(angle + tiltY).toFixed(2)}deg) rotateZ(${((1 - flip) * -3).toFixed(2)}deg) scale(${scale.toFixed(4)})`;
      stage.style.opacity = rise.toFixed(3);
      const climb = ease((t - CHARGE) / (FLIP - CHARGE - 60));
      backScan.style.opacity = t > CHARGE && t < FLIP ? "1" : "0";
      backScan.style.top = `${(12 + (1 - climb) * BACK_SCAN).toFixed(1)}px`;
      backFill.style.height = `${(climb * BACK_SCAN).toFixed(1)}px`;
      const tell = inCubic(charge);
      edge.style.setProperty("--edge", `rgba(${Math.round(220 - 4 * tell)},${Math.round(213 + 22 * tell)},${Math.round(233 - 127 * tell)},${(0.65 + 0.35 * tell).toFixed(3)})`);
      edge.style.setProperty("--glow", `${(tell * 28).toFixed(1)}px`);
      const bloom = t > FLIP ? Math.exp(-Math.max(0, t - FLIP - 200) / 500) : 0;
      halo.style.opacity = (tell * 0.55 + bloom * 0.6 + idle * 0.18).toFixed(3);
      halo.style.transform = `scale(${(0.7 + tell * 0.3 + bloom * 0.35).toFixed(3)})`;
      const raysOn = t > FLIP ? Math.min(1, (t - FLIP) / 200) : tell * 0.25;
      rays.style.opacity = (raysOn * (0.35 + 0.65 * Math.exp(-Math.max(0, t - FLIP - 300) / 900)) * (1 - 0.55 * idle)).toFixed(3);
      rays.style.transform = `rotate(${(t * 6e-3).toFixed(2)}deg) scale(${(1 + bloom * 0.15).toFixed(3)})`;
      const wave = clamp((t - FLIP - 180) / 700);
      ring.style.opacity = t > FLIP + 180 ? ((1 - wave) * 0.9).toFixed(3) : "0";
      ring.style.transform = `scale(${(0.6 + outExpo(wave) * 5.5).toFixed(3)})`;
      flash.style.opacity = t > FLIP + 150 ? (Math.max(0, 1 - (t - FLIP - 150) / 380) * 0.85).toFixed(3) : "0";
      const sw = clamp((t - FLIP_END + 120) / 650);
      sweep.style.opacity = sw > 0 && sw < 1 ? Math.sin(Math.PI * sw).toFixed(3) : "0";
      sweep.style.transform = `translateX(${(-60 + sw * 120).toFixed(1)}%)`;
      const flare = t > STARS_AT + 950 ? Math.exp(-(t - STARS_AT - 950) / 700) : 0;
      holo.style.opacity = (clamp((t - FLIP_END) / 500) * (0.22 + 0.1 * Math.sin(t / 900)) + flare * 0.35).toFixed(3);
      holo.style.backgroundPosition = `${(50 + tiltY * 6 + Math.sin(t / 1700) * 18).toFixed(1)}% ${(50 + tiltX * 6).toFixed(1)}%`;
      glare.style.opacity = (idle * 0.55).toFixed(3);
      glare.style.setProperty("--gx", `${(50 - tiltY * 5).toFixed(1)}%`);
      glare.style.setProperty("--gy", `${(30 + tiltX * 5).toFixed(1)}%`);
      rim.style.opacity = (clamp((t - STARS_AT - 1e3) / 500) * (0.55 + 0.25 * Math.sin(t / 700))).toFixed(3);
      rim.style.setProperty("--rim", `${(t / 18 % 360).toFixed(1)}deg`);
      const scan = clamp((t - PRINT_AT) / PRINT);
      art.style.clipPath = `inset(${((1 - scan) * 100).toFixed(2)}% 0 0 0)`;
      const sheen = `${(50 + tiltY * 7 + Math.sin(t / 1600) * 22).toFixed(1)}% ${(50 + tiltX * 7).toFixed(1)}%`;
      etch.style.opacity = (clamp((t - FLIP_END - 300) / 600) * (0.28 + 0.12 * Math.sin(t / 800))).toFixed(3);
      etch.style.backgroundPosition = `0 0, ${sheen}`;
      etch.style.setProperty("mask-position", sheen);
      etch.style.setProperty("-webkit-mask-position", sheen);
      stars.forEach((star, i) => {
        const k = (t - (STARS_AT + i * STAR_STEP)) / 320;
        const lit = i < setting.stars && k >= 0;
        star.classList.toggle("lit", lit);
        star.style.transform = `scale(${(!lit ? i < setting.stars ? 0.4 : 1 : k < 1 ? 2.2 - 1.2 * outBack(k) : 1).toFixed(3)})`;
      });
      const named = clamp((t - NAME_AT) / 500);
      name.style.opacity = ease(named).toFixed(3);
      name.style.transform = `translateY(${((1 - outExpo(named)) * 10).toFixed(1)}px)`;
      if (badge) {
        badge.style.opacity = ease(named).toFixed(3);
      }
      const hit = clamp((t - FLIP - 150) / 260);
      const amp = t > FLIP + 150 && hit < 1 ? (1 - hit) * 7 : 0;
      root.style.transform = amp ? `translate(${(Math.sin(t * 0.9) * amp).toFixed(2)}px,${(Math.cos(t * 1.3) * amp * 0.7).toFixed(2)}px)` : "";
      under.style.opacity = clamp((t - UNDER_AT) / 600).toFixed(3);
      if (!context) {
        return;
      }
      context.clearRect(0, 0, width, height);
      for (const p of INBOUND) {
        const k = (t - p.start) / p.life;
        if (k < 0 || k > 1) {
          continue;
        }
        const r = p.r * (1 - outExpo(k)) + 30;
        const x = cx + Math.cos(p.a) * r, y = cy + Math.sin(p.a) * r * 0.8;
        context.globalAlpha = Math.sin(Math.PI * k) * 0.9;
        context.fillStyle = context.strokeStyle = k > 0.6 ? "#e4f09c" : "#dcd5e9";
        context.beginPath();
        context.arc(x, y, p.size, 0, 7);
        context.fill();
        context.globalAlpha *= 0.35;
        context.lineWidth = p.size * 0.8;
        context.beginPath();
        context.moveTo(x, y);
        context.lineTo(cx + Math.cos(p.a) * (r + 26), cy + Math.sin(p.a) * (r + 26) * 0.8);
        context.stroke();
      }
      for (const p of BURST) {
        const k = (t - FLIP - 160) / p.life;
        if (k < 0 || k > 1) {
          continue;
        }
        const r = 40 + outExpo(k) * 520 * p.v;
        context.globalAlpha = (1 - k) * 0.95;
        context.fillStyle = p.lime ? "#e4f09c" : "#ffffff";
        context.beginPath();
        context.arc(cx + Math.cos(p.a) * r, cy + Math.sin(p.a) * r * 0.85 + k * k * 60, p.size * (1 - k * 0.5), 0, 7);
        context.fill();
      }
      for (const g of GLINTS) {
        const k = (t + g.phase) % g.period / g.period;
        if (idle <= 0 || k > 0.18) {
          continue;
        }
        const a = Math.sin(Math.PI * k / 0.18) * idle;
        const x = cx - 150 + g.x * 300, y = cy - 200 + g.y * 400;
        context.globalAlpha = a * 0.9;
        context.strokeStyle = "#f6fbd8";
        context.lineWidth = 1;
        context.beginPath();
        context.moveTo(x - 6 * a, y);
        context.lineTo(x + 6 * a, y);
        context.moveTo(x, y - 6 * a);
        context.lineTo(x, y + 6 * a);
        context.stroke();
      }
      for (const b of starBursts) {
        for (const p of STAR_SPARK) {
          const r = 6 + outExpo(b.k) * 42 * p.v;
          context.globalAlpha = (1 - b.k) * 0.95;
          context.fillStyle = "#eef7b8";
          context.beginPath();
          context.arc(b.x + Math.cos(p.a) * r, b.y + Math.sin(p.a) * r, 1.6 * (1 - b.k * 0.6), 0, 7);
          context.fill();
        }
      }
      context.globalAlpha = 1;
    }
    let disposed = false;
    let started = false;
    let animation;
    let wait;
    const play = () => {
      if (disposed || started) {
        return;
      }
      started = true;
      if (wait !== void 0) {
        mainWindow.clearTimeout(wait);
      }
      let start;
      const tick = (now) => {
        start ??= now;
        const t = Math.min(now - start, SETTLED_MS);
        frame(t);
        animation = t < SETTLED_MS && !disposed ? mainWindow.requestAnimationFrame(tick) : void 0;
      };
      animation = mainWindow.requestAnimationFrame(tick);
    };
    if (at !== void 0) {
      frame(clamp(at, 0, SETTLED_MS));
    } else if (mainWindow.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      frame(SETTLED_MS);
    } else {
      frame(0);
      art.decode().then(play, play);
      wait = mainWindow.setTimeout(play, ART_WAIT_MS);
    }
    return {
      say: (text) => {
        state.textContent = text;
      },
      dispose: () => {
        disposed = true;
        if (animation !== void 0) {
          mainWindow.cancelAnimationFrame(animation);
        }
        if (wait !== void 0) {
          mainWindow.clearTimeout(wait);
        }
        root.remove();
      }
    };
  }
  return __toCommonJS(opening_exports);
})();
