/** Derive the committed settings schema from the Zod document, using its locked dependency. */
import { writeFileSync } from 'node:fs';
import { z } from 'zod';
import { EditorSettingsSchema } from '../src/settings/schema.ts';

const schema = {
  $comment: 'AUTO-GENERATED by packages/project/scripts/generate-schema.mjs — do not edit manually',
  ...z.toJSONSchema(EditorSettingsSchema, { io: 'input' }),
};
writeFileSync(new URL('../schemas/volter-settings.schema.json', import.meta.url), JSON.stringify(schema, null, 2) + '\n');
